prof/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.index,name='index'),
    path('about/',views.about,name='about'),
    path('error/',views.error,name='error'),
    path('courses/',views.courses,name='courses'),
    path('contact/',views.contact,name='contact'),
    path('contactUs/',views.contactUs,name='contactUs'),
    path('contactEtd/',views.contactEtd,name='contactEtd'),
    path('team/',views.team,name='team'),
    path('profil/',views.profil,name='profil'),
    path('modProfil/',views.modProfil,name='modProfil'),
    path('header/',views.testNav,name='header'),
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('home/',views.homeProf,name='homeProf'),
    path('ajoutCours/',views.ajoutCours,name='ajoutCours'),
    path('delAllCourses/',views.delAllCourses,name='delAllCourses'),
    path('delAllChapters/',views.delAllChapters,name='delAllChapters'),
    path('afficherCourse/',views.afficherCourse,name='afficherCourse'),
    path('modCourse/',views.modCourse,name='modCourse'),
    path('ajoutChapitre/',views.ajoutChapitre,name='ajoutChapitre'),
    path('ajoutQuestion/',views.ajoutQuestion,name='ajoutQuestion'),
    path('afficherQuestion/',views.afficherQuestion,name='afficherQuestion'),
    path('modQuestion/',views.modQuestion,name='modQuestion'),
    path('delQuestion/',views.delQuestion,name='delQuestion'),    
    path('delAllQuestions/',views.delAllQuestions,name='delAllQuestions'),    
    path('delCourse/',views.delCourse,name='delCourse'),    
    path('afficherChapitre/',views.afficherChapitre,name='afficherChapitre'),
    path('delChapitre/',views.delChapitre,name='delChapitre'),
    path('modChapitre/',views.modChapitre,name='modChapitre'),
    #***************************************************************************************************
    path('indexEtd', views.indexEtd, name='indexEtd'),
    path('nav/',views.nav,name='nav'),
    path('coursesEtd/',views.coursesEtd,name='coursesEtd'),
    path('course/', view=views.CourseListView.as_view(), name='course'),
    path('profilEtd/',views.profilEtd,name='profilEtd'),
    path('modProfilEtd/',views.modProfilEtd,name='modProfilEtd'),
    path('<int:course_id>/desinscrire/',views.desinscrit,name='desinscrire'),
    path('<int:pk>/', views.CourseDetailView.as_view(), name='course_details'),
    path('<int:course_id>/inscrit/', views.inscrit, name='inscrit'),
    path('<int:course_id>/submit/', views.submit, name='submit'),
    path('<int:course_id>/rate/',views.rate,name='rate'),
    path('course/<int:course_id>/submission/<int:submission_id>/result/', views.show_exam_result, name='show_exam_result'),
]

profs/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('prof/', include('prof.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

prof/models.py
from django.db import models

# Create your models here.
class User(models.Model):  
    email = models.EmailField()
    password = models.CharField(max_length=255)
    role=models.CharField(max_length=20,choices=[('etd','etd'),('prof','prof')],default='etd')
    


class Etudiant(User):
    nom = models.CharField(max_length=50,default='Aucun')
    prenom = models.CharField(max_length=50,default='Aucun')
    telephone=models.CharField(max_length=10,null=True,blank=True,default='Aucun')
    linkedin=models.CharField(max_length=100,null=True,blank=True,default='Aucun')
    twitter=models.CharField(max_length=100,null=True,blank=True,default='Aucun')
    sexe=models.CharField(max_length=20,choices=[('Femme','Femme'),('Homme','Homme')],default='Homme')
    photo=models.ImageField(upload_to='photo/etds/%y/%m/%d',default='photo/etds/default_user.jpg')
    LEVEL_CHOICES = [
        ('sans bac', 'sans bac'),
        ('bac', 'bac'),
        ('bac+2', 'bac+2'),
        ('bac+3', 'bac+3'),
        ('bac+5', 'bac+5'),
    ]
    NiveauEtude = models.CharField(max_length=10, null=False,choices=LEVEL_CHOICES,default='bac')
    def __str__(self):
        return self.nom
    
class Prof(User):
    nom = models.CharField(max_length=50,default='Aucun')
    prenom = models.CharField(max_length=50,default='Aucun')
    telephone=models.CharField(max_length=10,null=True,blank=True,default='Aucun')
    linkedin=models.CharField(max_length=100,null=True,blank=True,default='Aucun')
    twitter=models.CharField(max_length=100,null=True,blank=True,default='Aucun')
    sexe=models.CharField(max_length=20,choices=[('Femme','Femme'),('Homme','Homme')],default='Homme')
    photo=models.ImageField(upload_to='photo/profs/%y/%m/%d',default='photo/profs/default_user.jpg')
    bio=models.TextField()
    def __str__(self):
        return self.nom
    
class Categorie(models.Model):
    CATEGORIE_CHOICES=[
        ('Informatique','Informatique'),
        ('Business','Business'),
        ('Droit','Droit'),
        ('Appretissange des langues','Appretissange des langues'),
    ]
    nom = models.CharField(max_length=255,choices=CATEGORIE_CHOICES,default='Informatique')
    photo=models.ImageField(upload_to='photo/categories/%y/%m/%d',default='photo/categories/default_cours.png')  
    def __str__(self):
        return self.nom

class Course(models.Model):
    titre=models.CharField(max_length=50)
    categorie=models.ForeignKey(Categorie,on_delete=models.PROTECT,null=True)
    datePub=models.DateField(auto_now_add=True)    
    description=models.TextField()
    fichier=models.FileField(upload_to="support//%y/%m/%d",null=True,default=None)
    photo=models.ImageField(upload_to='photo/cours/%y/%m/%d',default='photo/cours/default_cours.png')
    prof=models.ForeignKey(Prof,on_delete=models.PROTECT,null=True)
    nombreEtds = models.IntegerField(editable=True,default=0)
    nombreChaps = models.IntegerField(editable=True,default=0)
    nombreQues = models.IntegerField(editable=True,default=0)
    avgRate = models.DecimalField(max_digits=5,decimal_places=2,editable=False,default=0)
    def __str__(self):
        return self.titre

class Question(models.Model):
    text=models.TextField()
    note=models.IntegerField(default=1)
    course=models.ForeignKey(Course,on_delete=models.PROTECT,null=True)    
    def __str__(self):
        return self.text 
    def is_get_score(self, selected_ids):
        all_answers = self.choice_set.filter(correct=True).count()
        selected_correct = self.choice_set.filter(correct=True, id__in=selected_ids).count()
        if all_answers == selected_correct:
            return True
        else:
            return False
    
class Choice(models.Model):
    text=models.TextField()
    correct=models.BooleanField()
    question=models.ForeignKey(Question,on_delete=models.PROTECT,null=True)    
    def __str__(self):
        return self.text 
    
class Chapter(models.Model):
    titre=models.CharField(max_length=50)
    description=models.TextField()
    video=models.FileField(upload_to='video/cours/%y/%m/%d',verbose_name='contenu')
    course=models.ForeignKey(Course,on_delete=models.PROTECT,null=True)
    def __str__(self):
        return self.titre
    
class Inscription(models.Model):
    etudiant = models.ForeignKey(Etudiant, on_delete=models.PROTECT)
    course = models.ForeignKey(Course, on_delete=models.PROTECT)
    date_inscription = models.DateField(auto_now_add=True)
    rating = models.IntegerField(null=True,blank=True,default=-1)
    comment = models.TextField(null=True,blank=True,default="Aucun")
    score=models.DecimalField(max_digits=5,decimal_places=2,default=-1)
    def __str__(self):
        return self.course.titre

class Submission(models.Model):
   inscription = models.ForeignKey(Inscription, on_delete=models.PROTECT)
   choices = models.ManyToManyField(Choice)
   

class Notification(models.Model):
    titre = models.CharField(max_length=50)
    description = models.CharField(max_length=255)
    prof = models.ForeignKey(Prof, on_delete=models.PROTECT)
    def __str__(self):
        return self.titre

templates/etd/contactEtd.html
{% load static %}
{% include 'headerEtd.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <title>login</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/wow/wow.min.js' %}"></script>
    <script src="{% static 'lib/easing/easing.min.js ' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    
</head>
<body>
    <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Chargement ...</span>
        </div>
    </div>
<section>
    <div class="rowx">
            <h1 class="wlc2"><b>Contactez-nous</b></h1>
        </div>
    <div class="container">
        <div class="rowx">
            <label for="infos">Si vous avez des demandes commerciales ou d'autres questions, veuillez envoyer un e-mail à: <b>infos@corsiline.com</b> .</label>          
        </div>
       
    </div>

<br>
<center>
    <button class="btn btn-secondary" onclick="history.back()">Retour</button>
</center>
</section>



</body>
</html>

templates/etd/course_detail.html
{% include 'headerEtd.html' %}
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
          <meta charset="utf-8">
          <title>E-LEARNING - eLearning HTML Template</title>
          <meta content="width=device-width, initial-scale=1.0" name="viewport">
          <meta content="" name="keywords">
          <meta content="" name="description">
          <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
          <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
          <link href="{% static 'css/onlinecourse/bootstrap.min.css' %}" rel="stylesheet">
          <link href="{% static 'css/onlinecourse/navStyl.css'   %}" rel="stylesheet">
          <link href="{% static 'css/style.css'   %}" rel="stylesheet">
          <link href="{% static 'css/form.css'   %}" rel="stylesheet">
          <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
          <script src="{% static 'lib/wow/wow.min.js' %}"></script>
          <script src="{% static 'lib/easing/easing.min.js ' %}"></script>
          <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
          <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
          <script src="{% static 'js/main.js' %}"></script>
      </head>
      <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Chargement ...</span>
        </div>
    </div>
      
      <body><!--
        <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
          <a href="" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
              <h2 class="m-0 text-primary"><i class="fa fa-book me-3"></i>Corsiline</h2>
          </a>
          <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
              <div class="navbar-nav ms-auto p-4 p-lg-0">
                  <a href="{% url 'indexEtd' %}" class="nav-item nav-link active">Home</a>
                  <a href="{% url 'coursesEtd' %}" class="nav-item nav-link">Courses</a>
                  <a href="contact.html" class="nav-item nav-link">Contact</a>
              </div>
              <div class="nav-item dropdown">
                  <a href="" class="btn btn-primary py-4 px-lg-5 d-none d-lg-block">{{ user.prenom }} {{ user.nom }}<i class="fa fa-arrow-right ms-3"></i></a>
                  <div class="dropdown-menu fade-down m-0"> 
                  <a href="{% url 'logout' %}" class="nav-item nav-link active">Logout</a> 
                  <a href="{% url 'profilEtd' %}" class="nav-item nav-link active">Profile</a> 
            </div>
      </nav>-->
    <!-- Page content -->
    <section>
    <center>
    <div id="chapter" class="container-fluid" style="display: block;">
            <h2 class="ink" style="width:50%;font-size:40px;margin-top:0px;margin-bottom:20px;">{{ course.titre }}</h2>
            <div class="card-columns-vertical">
                {% for chapter in course.chapter_set.all %}
                    <div class="card mt-1">
                        <div class="card-header"><h5 class="ink" >Chapter {{ forloop.counter }} : {{chapter.titre}}</h5></div>
                        <div class="card-body"><b>Description : </b>{{chapter.description}}</div>
                        <div class="card-body">
                            <video controls>
                            <source src="{{chapter.video.url}}" type="video/mp4"></source>
                            </video>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <!-- Task: show questions and choices -->
            <!-- <HINT> Use Bootstrap Collapse to hide exam first, more details could be found here
            https://www.w3schools.com/bootstrap4/bootstrap_collapse.asp-->

            <!--

            A collapse example here:
            <div id="exam" class="collapse">
                Click to expand elements within the collapse div
                </div>

            -->
            <button id="start" data-toggle="collapse" data-target="#exam"
                 class="inkadd" role="button" style="margin-top: 10px;">Quiz</button>
    
                 <button class="inkdel" role="button" id="des">Désinscrire</button>
                 <script>
                    document.addEventListener('DOMContentLoaded', function() {
                        var button = document.getElementById('des');
                        button.addEventListener('click', function() {
                          var confirmed = confirm('Confirmez votre choix ??');
                          if (confirmed) {
                            window.location.href = '{% url 'desinscrire' course.id %}';  // Replace with your desired URL
                          }
                        });
                      });
                 </script>
    </div>
            <div id="exam" class="collapse" style="display: none;">
                
                    <form id="questionform" action="{% url 'submit' course.id %}" method="post">
                         {% for question in course.question_set.all %}
                        <div class="card mt-1" style="padding:15px 0px;">                         

                            <div class="card-header">
                                <h5 class="ink">Question {{ forloop.counter }} : {{question.text}}</h5>
                            </div>
                            {% csrf_token %}
                            <div class="container" style="font-size:20px;width:60%;">
                                {% for choice in question.choice_set.all %}
                                    <div class="form-check">
                                        <div class="rowx">
                                        <div class="col-25">
                                            <label><b>Choix {{ forloop.counter }}:</b></label>
                                        </div>
                                        <div class="col-75">
                                        <label class="form-check-label" style="float:left;">
                                            <input type="checkbox" name="choice_{{choice.id}}" class="form-check-input" id="{{choice.id}}"value="{{choice.id}}">
                                            {{ choice.text }}
                                        </label>
                                        </div>
                                        </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>                        
                        {% endfor %}
                        <br>
                         <button class="btn btn-success btn-block" type="submit" style="width: 10%; margin-top: 10px;" onclick="return confirm('Confirmez votre choix ?')">Envoyer</button>
                        </form>       
                        <button class="btn btn-secondary" style="width: 10%; margin-top: 10px;" onclick="location.reload()">Annuler</button>

            </div>
        </center>
    </section>
        <script>
            chapter = document.getElementById("chapter");
            question = document.getElementById("exam");
            start = document.getElementById("start")
            start.addEventListener('click', function() {               
                chapter.style.display = "none";
                question.style.display = "block";
          });

        </script>
        

   
</body>
</html>

templates/etd/exam_result.html
{% include 'headerEtd.html' %}

<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
          <meta charset="utf-8">
          <title>E-LEARNING - eLearning HTML Template</title>
          <meta content="width=device-width, initial-scale=1.0" name="viewport">
          <meta content="" name="keywords">
          <meta content="" name="description">
          <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
          <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
          <link href="{% static 'css/style.css' %}" rel="stylesheet">
          <link href="{% static 'css/style2.css' %}" rel="stylesheet">
          <link href="{% static 'css/form.css' %}" rel="stylesheet">
          <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
          <script src="{% static 'lib/wow/wow.min.js' %}"></script>
          <script src="{% static 'lib/easing/easing.min.js ' %}"></script>
          <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
          <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
          <script src="{% static 'js/main.js' %}"></script>
      </head>
      
      <body>
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Chargement ...</span>
            </div>
        </div>
    <!--
        <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
          <a href="{% url 'indexEtd' %}" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
              <h2 class="m-0 text-primary"><i class="fa fa-book me-3"></i>Corsiline</h2>
          </a>
          <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
              <div class="navbar-nav ms-auto p-4 p-lg-0">
                  <a href="{% url 'indexEtd' %}" class="nav-item nav-link active">Home</a>
                  <a href="{% url 'courses' %}" class="nav-item nav-link">Courses</a>
                  <a href="{% url 'contact' %}" class="nav-item nav-link">Contact</a>
              </div>
              <div class="nav-item dropdown">
                  <a href="" class="btn btn-primary py-4 px-lg-5 d-none d-lg-block">{{ user.prenom }} {{ user.nom }}<i class="fa fa-arrow-right ms-3"></i></a>
                  <div class="dropdown-menu fade-down m-0"> 
                  <a href="{% url 'logout' %}" class="nav-item nav-link active">Logout</a> 
                  <a href="{% url 'profilEtd' %}" class="nav-item nav-link active">Profile</a> 
            </div>
      </nav>
    -->
<section>
<div class="container-fluid" style="padding: 20px;">
    {% if note >= 80 %}
    <div class="alert alert-success">
       <!--HINT Display passed info -->
       <b>Félicitations, {{user.prenom}} {{user.nom}} ! </b>Vous avez réussi l'examen avec un score de {{note}}%
    </div>
        {% else %}
        <div class="alert alert-danger">
            <!--HINT Display failed info -->
            <b>Désolé, {{user.prenom}} {{user.nom}} ! </b>Vous avez échoué, votre score final est {{note}} %, moins de 80 % 
        </div>
        <label class="btn btn-link text-danger">Voulez-vous essayer à nouveau ?</label>    
        <label class="rep" onclick="location.href='{% url 'course_details' course.id %}'">Oui</label><label class="rep" onclick="history.back()" style="background:rgb(179, 54, 54);margin-left:0px;">Non</label>

        {% endif %}
        <div class="card-columns-vertical mt-1">
        <div class="card mt-1" style="text-align:center;">
            <div class="card-header" style=""><h5 class="ink" style="height:100%;margin:0;">Resultas d'examen</h5></div>
        </div>
            <!--HINT Display exam results-->
            {% for question in course.question_set.all %}
                <div class="card" style="margin: 20px;">
                    <div class="card-header border-light">
                        <h5>{{question.text}}</h5>
                    </div>
                    <div class="card-body">
                        {% for choice in question.choice_set.all %}
                        <ul style="list-style-type:circle;">
                           {% if choice.correct and choice in choices %}
                            <li ><p class="card-text" style="color:green"><b>{{choice.text}} = > Reponse correct !</b></p></li>
                            {% elif choice.correct and choice not in choices %}
                            <li><p class="card-text" style="color:orange">{{choice.text}} = > Non séléctionné :/ </p><il>
                            {% elif choice.correct == False and choice in choices %}
                            <li><p class="card-text" style="color:red">{{choice.text}} = > Reponse fausse :(</p> </li>
                            {% else %}
                            <li><p class="card-text" style="color:black">{{choice.text}}</p> </li>
                            {% endif %}
                        </ul>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        </div>

        {% if note >= 80 %}
        <div class="card mt-1" style="text-align:center;">
            <div class="card-header" style=""><h5 class="ink" style="height:100%;margin:0;">Rating</h5></div>
        </div>
        <div class="card" style="margin: 20px;">
            <div class="card-header border-light">
                <h5>Évaluez ce cours pour le terminer</h5>
            </div>
        <div class="card-body">
        <form action="{% url 'rate' course.id %}" method="post">
        {% csrf_token %}
        <div class="container" style="font-size:20px;width:70%;">
        <div class="rowx">
        <div class="col-25">
        <label for="rate">De 0 à 5 points</label>
        </div>
        <div class="col-75">
        <input name="rate" type="number" min="0" step="1" max="5" required>
        </div>
        </div>
        <div class="rowx">
            <div class="col-25">
            <label for="rate">Commentaire (facultatif)</label>
            </div>
            <div class="col-75">
            <textarea name="cmt"></textarea>
            </div>
        </div>
        <div class="rowx">
        <input type="submit" value="Terminer" style="width:40%;">
        </div>
        </div>

        </form>
    </div></div>
        {% else %}
        <center>
        <button type="button" class="btn btn-secondary" onclick="history.back()">Retour</button>
        </center>
        {% endif %}
    </div>
</section>

</body>
</html>

templates/etd/nav.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="utf-8">
    <title>E-LEARNING - eLearning HTML Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->

    <!-- Google Web Fonts -->
    

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/onlinecourse/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/onlinecourse/navStyl.css'   %}" rel="stylesheet">
</head>

<body>
    <!-- Spinner Start -->
    <!-- Spinner End -->
<nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
    <a href="" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
        <h2 class="m-0 text-primary"><i class="fa fa-book me-3"></i>Corsiline</h2>
    </a>
    <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav ms-auto p-4 p-lg-0">
            <a href="" class="nav-item nav-link active">Home</a>
            <a href="" class="nav-item nav-link">About</a>
            <a href="" class="nav-item nav-link">Courses</a>
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                <div class="dropdown-menu fade-down m-0">
                    <a href="" class="dropdown-item">Our Team</a>
                    <a href="" class="dropdown-item">Testimonial</a>
                    <a href="" class="dropdown-item">404 Page</a>
                </div>
            </div>
            <a href="contact.html" class="nav-item nav-link">Contact</a>
        </div>
        <a href="" class="btn btn-primary py-4 px-lg-5 d-none d-lg-block">Join Now<i class="fa fa-arrow-right ms-3"></i></a>
    </div>
</nav>
</body>
</html>