prof/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.index,name='index'),
    path('about/',views.about,name='about'),
    path('error/',views.error,name='error'),
    path('courses/',views.courses,name='courses'),
    path('contact/',views.contact,name='contact'),
    path('contactUs/',views.contactUs,name='contactUs'),
    path('contactEtd/',views.contactEtd,name='contactEtd'),
    path('team/',views.team,name='team'),
    path('profil/',views.profil,name='profil'),
    path('modProfil/',views.modProfil,name='modProfil'),
    path('header/',views.testNav,name='header'),
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('home/',views.homeProf,name='homeProf'),
    path('ajoutCours/',views.ajoutCours,name='ajoutCours'),
    path('delAllCourses/',views.delAllCourses,name='delAllCourses'),
    path('delAllChapters/',views.delAllChapters,name='delAllChapters'),
    path('afficherCourse/',views.afficherCourse,name='afficherCourse'),
    path('modCourse/',views.modCourse,name='modCourse'),
    path('ajoutChapitre/',views.ajoutChapitre,name='ajoutChapitre'),
    path('ajoutQuestion/',views.ajoutQuestion,name='ajoutQuestion'),
    path('afficherQuestion/',views.afficherQuestion,name='afficherQuestion'),
    path('modQuestion/',views.modQuestion,name='modQuestion'),
    path('delQuestion/',views.delQuestion,name='delQuestion'),    
    path('delAllQuestions/',views.delAllQuestions,name='delAllQuestions'),    
    path('delCourse/',views.delCourse,name='delCourse'),    
    path('afficherChapitre/',views.afficherChapitre,name='afficherChapitre'),
    path('delChapitre/',views.delChapitre,name='delChapitre'),
    path('modChapitre/',views.modChapitre,name='modChapitre'),
    #***************************************************************************************************
    path('indexEtd', views.indexEtd, name='indexEtd'),
    path('nav/',views.nav,name='nav'),
    path('coursesEtd/',views.coursesEtd,name='coursesEtd'),
    path('course/', view=views.CourseListView.as_view(), name='course'),
    path('profilEtd/',views.profilEtd,name='profilEtd'),
    path('modProfilEtd/',views.modProfilEtd,name='modProfilEtd'),
    path('<int:course_id>/desinscrire/',views.desinscrit,name='desinscrire'),
    path('<int:pk>/', views.CourseDetailView.as_view(), name='course_details'),
    path('<int:course_id>/inscrit/', views.inscrit, name='inscrit'),
    path('<int:course_id>/submit/', views.submit, name='submit'),
    path('<int:course_id>/rate/',views.rate,name='rate'),
    path('course/<int:course_id>/submission/<int:submission_id>/result/', views.show_exam_result, name='show_exam_result'),
]

profs/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('prof/', include('prof.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

prof/models.py
from django.db import models

# Create your models here.
class User(models.Model):  
    email = models.EmailField()
    password = models.CharField(max_length=255)
    role=models.CharField(max_length=20,choices=[('etd','etd'),('prof','prof')],default='etd')
    


class Etudiant(User):
    nom = models.CharField(max_length=50,default='Aucun')
    prenom = models.CharField(max_length=50,default='Aucun')
    telephone=models.CharField(max_length=10,null=True,blank=True,default='Aucun')
    linkedin=models.CharField(max_length=100,null=True,blank=True,default='Aucun')
    twitter=models.CharField(max_length=100,null=True,blank=True,default='Aucun')
    sexe=models.CharField(max_length=20,choices=[('Femme','Femme'),('Homme','Homme')],default='Homme')
    photo=models.ImageField(upload_to='photo/etds/%y/%m/%d',default='photo/etds/default_user.jpg')
    LEVEL_CHOICES = [
        ('sans bac', 'sans bac'),
        ('bac', 'bac'),
        ('bac+2', 'bac+2'),
        ('bac+3', 'bac+3'),
        ('bac+5', 'bac+5'),
    ]
    NiveauEtude = models.CharField(max_length=10, null=False,choices=LEVEL_CHOICES,default='bac')
    def __str__(self):
        return self.nom
    
class Prof(User):
    nom = models.CharField(max_length=50,default='Aucun')
    prenom = models.CharField(max_length=50,default='Aucun')
    telephone=models.CharField(max_length=10,null=True,blank=True,default='Aucun')
    linkedin=models.CharField(max_length=100,null=True,blank=True,default='Aucun')
    twitter=models.CharField(max_length=100,null=True,blank=True,default='Aucun')
    sexe=models.CharField(max_length=20,choices=[('Femme','Femme'),('Homme','Homme')],default='Homme')
    photo=models.ImageField(upload_to='photo/profs/%y/%m/%d',default='photo/profs/default_user.jpg')
    bio=models.TextField()
    def __str__(self):
        return self.nom
    
class Categorie(models.Model):
    CATEGORIE_CHOICES=[
        ('Informatique','Informatique'),
        ('Business','Business'),
        ('Droit','Droit'),
        ('Appretissange des langues','Appretissange des langues'),
    ]
    nom = models.CharField(max_length=255,choices=CATEGORIE_CHOICES,default='Informatique')
    photo=models.ImageField(upload_to='photo/categories/%y/%m/%d',default='photo/categories/default_cours.png')  
    def __str__(self):
        return self.nom

class Course(models.Model):
    titre=models.CharField(max_length=50)
    categorie=models.ForeignKey(Categorie,on_delete=models.PROTECT,null=True)
    datePub=models.DateField(auto_now_add=True)    
    description=models.TextField()
    fichier=models.FileField(upload_to="support//%y/%m/%d",null=True,default=None)
    photo=models.ImageField(upload_to='photo/cours/%y/%m/%d',default='photo/cours/default_cours.png')
    prof=models.ForeignKey(Prof,on_delete=models.PROTECT,null=True)
    nombreEtds = models.IntegerField(editable=True,default=0)
    nombreChaps = models.IntegerField(editable=True,default=0)
    nombreQues = models.IntegerField(editable=True,default=0)
    avgRate = models.DecimalField(max_digits=5,decimal_places=2,editable=False,default=0)
    def __str__(self):
        return self.titre

class Question(models.Model):
    text=models.TextField()
    note=models.IntegerField(default=1)
    course=models.ForeignKey(Course,on_delete=models.PROTECT,null=True)    
    def __str__(self):
        return self.text 
    def is_get_score(self, selected_ids):
        all_answers = self.choice_set.filter(correct=True).count()
        selected_correct = self.choice_set.filter(correct=True, id__in=selected_ids).count()
        if all_answers == selected_correct:
            return True
        else:
            return False
    
class Choice(models.Model):
    text=models.TextField()
    correct=models.BooleanField()
    question=models.ForeignKey(Question,on_delete=models.PROTECT,null=True)    
    def __str__(self):
        return self.text 
    
class Chapter(models.Model):
    titre=models.CharField(max_length=50)
    description=models.TextField()
    video=models.FileField(upload_to='video/cours/%y/%m/%d',verbose_name='contenu')
    course=models.ForeignKey(Course,on_delete=models.PROTECT,null=True)
    def __str__(self):
        return self.titre
    
class Inscription(models.Model):
    etudiant = models.ForeignKey(Etudiant, on_delete=models.PROTECT)
    course = models.ForeignKey(Course, on_delete=models.PROTECT)
    date_inscription = models.DateField(auto_now_add=True)
    rating = models.IntegerField(null=True,blank=True,default=-1)
    comment = models.TextField(null=True,blank=True,default="Aucun")
    score=models.DecimalField(max_digits=5,decimal_places=2,default=-1)
    def __str__(self):
        return self.course.titre

class Submission(models.Model):
   inscription = models.ForeignKey(Inscription, on_delete=models.PROTECT)
   choices = models.ManyToManyField(Choice)
   

class Notification(models.Model):
    titre = models.CharField(max_length=50)
    description = models.CharField(max_length=255)
    prof = models.ForeignKey(Prof, on_delete=models.PROTECT)
    def __str__(self):
        return self.titre

templates/prof/ajoutChapitre.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <title>Ajout Chapitre</title>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'lib/wow/wow.min.js' %}"></script>
<script src="{% static 'lib/easing/easing.min.js ' %}"></script>
<script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
<script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</head>
<body>
  <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
    <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
        <span class="sr-only">Chargement ...</span>
    </div>
</div>
<section>
  <div class="rowx">
    <h1 class="wlc2"><b>Ajouter un chapitre</b></h1>
</div>
<div class="container">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
   
    <div class="rowx">
    <div class="col-25">
    <label for="id_title">Titre du chapitre:</label>
    </div>  
    <div class="col-75">
    <input type="text" name="titre" id="id_title" required>
    </div>
    </div>

    <div class="rowx">
    <div class="col-25">
    <label for="id_description">Description:</label>
    </div>  
    <div class="col-75">
    <textarea name="desc" id="id_description" required></textarea>
    </div>
    </div>

    <div class="rowx">
    <div class="col-25">
    <label for="contenu">Contenu du chapitre (mp4):</label>
    </div>
    <div class="col-75">
    <input type="file" name="contenu" accept="application/mp4" required>
    </div>
    </div>
    <div class="rowx">
        <input type="submit" value="Ajouter Chapitre"></input>
    </div>
  </form>
</div>
<br>
<center>

{% if chapter_added %}
<script>
    var addChapters = confirm("Chapitre ajouté avec succès ! Voulez-vous ajouter un autre?");
    if (addChapters) {
      location.href = "{% url 'ajoutChapitre'%}?course_id={{course_id}}";
    } else {
      location.href = "{% url 'homeProf' %}";
    }
</script>
{% endif %}

<button class="ink" onclick="location.href='{% url 'afficherCourse' %}?course_id={{ course_id }}';">Annuler</button>
</center>
</section>
</body>
</html>
{% endblock content %}

templates/prof/ajoutCours.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <title>Ajout cours</title>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'lib/wow/wow.min.js' %}"></script>
<script src="{% static 'lib/easing/easing.min.js ' %}"></script>
<script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
<script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

<script src="{% static 'js/main.js' %}"></script>
</head>
<body>
  <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
    <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
        <span class="sr-only">Chargement ...</span>
    </div>
</div>
<section>
  <div class="rowx">
    <h1 class="wlc2"><b>Ajouter un cours</b></h1>
</div>
<div class="container">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
   
    <div class="rowx">
    <div class="col-25">
    <label for="id_title">Titre du cours:</label>
    </div>  
    <div class="col-75">
    <input type="text" name="titre" id="id_title" required>
    </div>
    </div>

    <div class="rowx">
      <div class="col-25">
      <label for="cat">Categorie du cours:</label>
      </div>  
      <div class="col-75">
        <select name="cat" id="cat">
          {% for c in categories %}
          <option value="{{c.id}}">{{c.nom}}</option>
          {% endfor %}
        </select>
      </div>
    </div>

    <div class="rowx">
    <div class="col-25">
    <label for="id_description">Description:</label>
    </div>  
    <div class="col-75">
    <textarea name="desc" id="id_description" required></textarea>
    </div>
    </div>

    <div class="rowx">
    <div class="col-25">
    <label for="support">Support du cours (PDF):</label>
    </div>
    <div class="col-75">
    <input type="file" name="support" accept="application/pdf" required>
    </div>
    </div>

    <div class="rowx">
    <div class="col-25">
    <label for="id_image">Image:</label>
    </div>
    <div class="col-75">
    <input type="file" name="image" id="id_image" accept="image/*">
    </div>
    </div>
    <div class="rowx">
        <input type="submit" value="Ajouter Cours"></input>
    </div>
  </form>
</div>
<br>
<center>
{% if course_added %}
<script>
    var addChapters = confirm("Cours ajouté avec succès ! Voulez-vous ajouter ses chapitres maintenant?");
    if (addChapters) {
      location.href = "{% url 'ajoutChapitre' %}?course_id={{course_id}} ";
    } else {
      location.href = "{% url 'homeProf' %}";
    }
</script>
{% endif %}

<button class="ink" onclick="location.href='{% url 'homeProf' %}';">Annuler</button>
</center>
</section>
</body>
</html>
{% endblock content %}

templates/prof/ajoutQuestion.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <title>Ajout Question</title>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'lib/wow/wow.min.js' %}"></script>
<script src="{% static 'lib/easing/easing.min.js ' %}"></script>
<script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
<script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

<script src="{% static 'js/main.js' %}"></script>
</head>
<body>
    <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Chargement ...</span>
        </div>
    </div>
    <section>
    <div class="rowx">
        <h1 class="wlc2"><b>Ajouter une question</b></h1>
    </div>
<div class="container">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    <br>
    <div class="rowx">
        <h3 class="profil_title"><b>La question:</b></h3>
    </div>
    
    <div class="rowx">
    <div class="col-25">
        <label for="ques">Text du question:</label>
    </div>  
    <div class="col-75">
    <textarea name="ques" id="ques" placeholder="votre question" required></textarea>
    </div>
    </div>
  
    <br>
    <div class="rowx">
        <h3 class="profil_title"><b>Les choix:</b></h3>
    </div>

    <div class="rowx">
        <div class="col-25">
            <label for="choix1">Choix 1:</label>
        </div>  
        <div class="col-75">
        <input type="text" name="choix1" id="choix1" placeholder="Choix numero 1"><br>
        <label class="sexe" for="correct1" >Correct</label>
        <input type="radio" id="correct1" name="cor1" value="Correct" checked>
        <label class="sexe" for="incorrect1">Incorrect</label>
        <input type="radio" id="incorrect1" name="cor1" value="Incorrect">
        </div>
    </div>

    <div class="rowx">
        <div class="col-25">
            <label for="choix2">Choix 2:</label>
        </div>  
        <div class="col-75">
        <input type="text" name="choix2" id="choix2" placeholder="Choix numero 2"><br>
        <label class="sexe" for="correct2">Correct</label>
        <input type="radio" id="correct2" name="cor2" value="Correct" checked>
        <label class="sexe" for="incorrect2">Incorrect</label>
        <input type="radio" id="incorrect2" name="cor2" value="Incorrect">
        </div>
    </div>

    <div class="rowx">
        <div class="col-25">
            <label for="choix3">Choix 3:</label>
        </div>  
        <div class="col-75">
        <input type="text" name="choix3" id="choix3" placeholder="Choix numero 3"><br>
        <label class="sexe" for="correct3">Correct</label>
        <input type="radio" id="correct3" name="cor3" value="Correct" checked> 
        <label class="sexe" for="incorrect3">Incorrect</label>
        <input type="radio" id="incorrect3" name="cor3" value="Incorrect">
        </div>
    </div>

    <div class="rowx">
        <div class="col-25">
            <label for="choix4">Choix 4:</label>
        </div>  
        <div class="col-75">
        <input type="text" name="choix4" id="choix4" placeholder="Choix numero 4"><br>
        <label class="sexe" for="correct4">Correct</label>
        <input type="radio" id="correct4" name="cor4" value="Correct" checked>
        <label class="sexe" for="incorrect4">Incorrect</label>
        <input type="radio" id="incorrect4" name="cor4" value="Incorrect">
        </div>
    </div>

   

    <div class="rowx">
        <input type="submit" value="Ajouter Question"></input>
    </div>
  </form>
</div>
<br>
<center>

{% if question_added %}
<script>
    window.alert("Question ajouté avec succès");
    location.href="{% url 'afficherCourse' %}?course_id={{course_id}}";
</script>
{% endif %}

<button class="ink" onclick="history.back()">Annuler</button>
</center>
</section>
</body>
</html>
{% endblock content %}

templates/prof/contactPr.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <title>login</title>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'lib/wow/wow.min.js' %}"></script>
<script src="{% static 'lib/easing/easing.min.js ' %}"></script>
<script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
<script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

<script src="{% static 'js/main.js' %}"></script>
</head>
<body>
    <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Chargement ...</span>
        </div>
    </div>
<section>
    <div class="rowx">
            <h1 class="wlc2"><b>Contactez-nous</b></h1>
        </div>
    <div class="container">
        <div class="rowx">
            <label for="infos">Si vous avez des demandes commerciales ou d'autres questions, veuillez envoyer un e-mail à: <b>infos@corsiline.com</b> .</label>          
        </div>
       
    </div>

<br>
<center>
    <button class="btn btn-secondary" onclick="history.back()">Retour</button>
</center>
</section>
</body>
</html>
{% endblock %}

templates/prof/course_chapter.html
{% extends 'base.html' %} 
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="{% static 'css/form.css' %}">

    <title>Chapter</title>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'lib/wow/wow.min.js' %}"></script>
<script src="{% static 'lib/easing/easing.min.js ' %}"></script>
<script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
<script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

<script src="{% static 'js/main.js' %}"></script>
</head>
<body>
    <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Chargement ...</span>
        </div>
    </div>
<section>
    <div class="rowx">
        <h1 class="wlc2"><b>Details chapitre</b></h1>
    </div>
    <div id="chapter" class="container-fluid" style="display: block;">
        <center>
        <div class="card-columns-vertical">
                <div class="card mt-1">
                    <div class="card-header"><h5 class="ink" >Chapter : {{chapitre.titre}}</h5></div>
                    <div class="card-body"><b>Description : </b>{{chapitre.description}}</div>
                    <div class="card-body">
                        <video controls>
                        <source src="{{chapitre.video.url}}" type="video/mp4"></source>
                        </video>
                    </div>
                </div>
        </div>
    </center>
    </div>

<center>
<button class="ink" onclick="history.back()">Retour</button>
</center>

</section>
</body>

</html>
{% endblock content %}

templates/prof/del_prof_course.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'lib/wow/wow.min.js' %}"></script>
<script src="{% static 'lib/easing/easing.min.js ' %}"></script>
<script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
<script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

<script src="{% static 'js/main.js' %}"></script>
</head>
<body>
    <h1>Delete</h1>
    
</body>
</html>

templates/prof/modChapter.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <title>Modifier Chapitre</title>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'lib/wow/wow.min.js' %}"></script>
<script src="{% static 'lib/easing/easing.min.js ' %}"></script>
<script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
<script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

<script src="{% static 'js/main.js' %}"></script>
</head>
<body>
    <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Chargement ...</span>
        </div>
    </div>
<section>
    <div class="rowx">
        <h1 class="wlc2"><b>Modifier un chapitre</b></h1>
    </div>
<div class="container">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="rowx">
    <div class="col-25">
    <label for="id_title">Titre du Chapitre:</label>
    </div>  
    <div class="col-75">
    <input type="text" name="titre" id="id_title" defaultValue="{{ chapter.titre }}" value="{{ chapter.titre }}" required>
    </div>
    </div>

    <div class="rowx">
    <div class="col-25">
    <label for="id_description">Description:</label>
    </div>  
    <div class="col-75">
    <textarea name="desc" id="id_description" defaultValue="{{ chapter.description }}" required>{{ chapter.description }}</textarea>
    </div>
    </div>

    <div class="rowx">
    <div class="col-25">
    <label onclick="vid()">Changer le contenu actuel ?</label>
    </div>
    <div class="col-75">
    <label class="rep" onclick="vid()" id="rep">Oui</label>
    <input type="file" id="contenu" name="contenu" style="visibility:hidden;" accept="application/mp4">
    </div>
    </div>
    <div class="rowx">
        <input type="submit" value="Modifier Chapitre" onclick="return confirm('Voulez-vous modifier ce chapitre ?')">
    </div>
  </form>
</div>
<br>
<center>
{% if chap_mod %}
<script>
    alert("Chapitre modifié avec succès !");
    location.href = "{% url 'homeProf' %}";

</script>
{% endif %}
<script>
   
    function vid(){
        if(document.getElementById("rep").innerHTML == "Oui"){
        document.getElementById("contenu").style.visibility = "visible";
        //document.getElementById("rep").style.visibility = "hidden";
        document.getElementById("rep").innerHTML="Non"
        document.getElementById("rep").style.background="rgb(179, 54, 54)"

        }
        else{
        document.getElementById("contenu").style.visibility = "hidden";
        document.getElementById("rep").innerHTML="Oui"
        document.getElementById("rep").style.background="green"
        }
        
    }
</script>
<button class="ink" onclick="history.back()">Annuler</button>
</center>
</section>
</body>
</html>
{% endblock content %}